config/routes.rb
Emmo::Application.routes.draw do
  
  get "static_pages/help"
  get "users/show_create"

  get  "login"    => "sessions#new"
  get  "register" => "users#new"
  get  "home"     => "static_pages#home"
  get  "about"    => "static_pages#about"
  get  "setting"  => "settings#index"

  delete "sessions" => "sessions#destroy"

  root "sessions#new"

  resources :users 
  resources :sessions 
  resources :books
  resources :friends

end

app/models/friendships.rb
class Friendships < ActiveRecord::Base



  def self.be_friends(user, friend)
    user.friends << friend
    friend.friends << user
  end

  def self.break_off(user, friend)
    Friendships.where(friend_id:friend, user_id:user).destroy_all
    Friendships.where(friend_id:user, user_id:friend).destroy_all
  end

end

app/models/record.rb
class Record < ActiveRecord::Base


  validates :owner, presence: true
  validates :payer, presence: true
  validates :recorder, presence: true
  validates :time, presence: true
  validates :note, presence: true
  validates :tag, presence: true
  

  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"
  belongs_to :payer, :class_name => "User", :foreign_key => "payer_id"
  belongs_to :recorder, :class_name => "User", :foreign_key => "recorder_id"
    

  def attr_name attribute
    attribute
  end

  def error_messages
    [] unless self.errors.any?
    
    msgs = []
    self.errors.messages.each do |attribute, messages|
      messages.each do |m|
        msgs.push( "#{self.attr_name(attribute)} #{m}" )
      end
    end
    msgs
  end

end

app/models/user.rb
class User < ActiveRecord::Base


  before_create :create_remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, 
    presence: true, 
    length: { maximum: 20 }
  validates :email, 
    presence: true, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  #validates :password_digest

  has_many :own_records, :class_name => "Record", :foreign_key => "owner_id"
  has_many :pay_records, :class_name => "Record", :foreign_key => "payer_id"
  has_many :rec_records, :class_name => "Record", :foreign_key => "recorder_id"

  # http://www.ptt.cc/man/Ruby/D8A0/D23C/DCFC/M.1171361058.A.F08.html
  has_and_belongs_to_many :friends, :class_name => "User", :join_table => "friendships", :association_foreign_key => "friend_id", :foreign_key => "user_id"

  has_secure_password

  def attr_name attribute
    case attribute
    when :name
      "暱稱"
    when :email
      "信箱"
    when :password
      "密碼"
    end
  end

  def error_messages
    [] unless self.errors.any?
    
    msgs = []
    self.errors.messages.each do |attribute, messages|
      messages.each do |m|
        msgs.push( "#{self.attr_name(attribute)} #{m}" )
      end
    end
    msgs
  end

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  #def gravatar_for(user)
  #  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #  image_tag(gravatar_url, alt: user.name, class: "gravatar")
  #end

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email.downcase)
    "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end


  def add_friend(friend)
    Friendships.be_friends(self, friend)
  end

  def remove_friend(friend)
    Friendships.break_off(self, friend)
  end


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    #@record = Record.new(record_params)

    return render :json => {:error => "Illegal authorization"} unless signed_in?

    render :json => Record.new(record_params)

    if @record.save
      # Handle a successful save.
    else
      #@errors = @record.error_messages
      #render 'index'
    end

    render :json => {msg: "ok"}
  end

  def new
    
  end

  private 

    def record_params
      begin 
        params.require(:record).permit(:time, :money, :recoder, :payer, :owner, :note)
      rescue
        nil
      end
    end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout "layouts/pure", :only => [:create, :new]

  

  def new
    if signed_in?
      redirect_to home_path
    end
  end


  def create 
    user = User.find_by_email(params[:session][:email].downcase)
    if user and user.authenticate(params[:session][:password]) then
      sign_in user
      redirect_to home_path
    else
      @errors = ["信箱或密碼可能錯了！"]
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end


end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if not signed_in?
      redirect_to root_path
    end
  end

  def help
  end

  def about

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  layout "layouts/pure", :only => [:login, :register]


  def login
  end

  def register
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "layouts/pure", :only => [:new, :create, :show_create]


  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # Handle a successful save.
    else
      @errors = @user.error_messages
      render 'new'
    end
  end

  def show_create
    @user = User.new name: "test User"
    render 'create'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = {
      value: remember_token,
      expires: 7.days.from_now.utc
    }
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def home

  end



end

app/helpers/user_helper.rb
module UserHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper

  
end

app/views/books/index.html.erb
<% provide :sidebar_active_item, 'books' %>
<% provide :page_title_text, '我的記帳本' %>
<% provide :page_title_icon, 'book' %>

<!-- <i class="emmo-popup heart circular icon link" title="Hello, I am a pop-up."></i> -->

<table class="ui padded basic table segment " id="bookRecordTable">
  <thead>
    <tr>
      <th>時間</th>
      <th>金額</th>
      <th>事項</th>
    </tr>
  </thead>
  <tbody>
    <tr class="emmo-popup" title="記錄人：Honda">
      <td>2013-12-11 (三)</td>
      <td>No Name Specified</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <td>2013-12-11 (三)</td>
      <td>Jimmy</td>
      <td> Approved</td>
    </tr>
    <tr>
      <td>2013-12-11 (三)</td>
      <td>Jamie</td>
      <td>Unknown</td>
    </tr>
    <tr>
      <td>2013-12-11 (三)</td>
      <td>Jill</td>
      <td>Unknown</td>
    </tr>
  </tbody>
  <!--
  <tfoot>
    <tr>
      <th colspan="4">
        
      </th>
    </tr>
  </tfoot>
  -->
</table>

<div id="emmo-add-record-button" class="ui teal small labeled icon button "><i class="plus icon"></i> 加入資料</div>


<div class="ui styled wide sidebar emmo-web-sidebar ">
  <i class="close icon emmo-right-icon"></i>
  <!--
  <h3 class="ui header">You Might Like</h3>
  <div class="ui fluid vertical menu">
    <a class="item">
      <i class="chat outline icon"></i>
      More by this author
    </a>
    <a class="item">
      <i class="text file icon"></i>
      Suggested Articles
    </a>
  </div>
  -->
  <h3 class="ui header">新增一筆資料</h3>
  <div class="ui form">
    <div class="field" id="emmo-record-time">
      <label>時間</label>
      <div class="ui selection fluid dropdown">
        <input type="hidden" name="gender">
        <i class="time icon"></i>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="1">Male</div>
          <div class="item active" data-value="0">AA</div>
        </div>
      </div>
    </div>
    <div class="field">
      <label>付款人</label>
      <div class="ui selection fluid dropdown">
        <input type="hidden" name="gender">
        <i class="cart icon"></i>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="1">Honda</div>
          <div class="item active" data-value="0">Sanae</div>
        </div>
      </div>
    </div>
    <div class="field">
      <label>幫誰付</label>
      <div class="ui selection fluid dropdown">
        <input type="hidden" name="gender">
        <i class="male icon"></i>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="1">Honda</div>
          <div class="item active" data-value="0">Sanae</div>
        </div>
      </div>
    </div>
    <div class="field">
      <label>分類</label>
      <div class="ui selection fluid dropdown">
        <input type="hidden" name="gender">
        <i class="tag icon"></i>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="1">早餐</div>
          <div class="item active" data-value="0">午餐</div>
        </div>
      </div>
      <!--
      <div class="ui input">
        <input placeholder="沒有適合的嗎？ 自己輸入一個吧！" />
      </div>
      -->
    </div>

    <div class="field">
      <label>金額</label>
      <div class="ui left icon input">
        <i class="dollar icon"></i>
        <input type="text" placeholder="" class="datepicker">
      </div>
    </div>


    <div class="field">
      <label>事項</label>
      <textarea></textarea>
    </div>
    <div class="ui black fluid button">加入</div>
  </div>
</div>


<script>



fakeDatas = function(n) {
  var a = []
  while(n-- >0)
    a.push({
      time: moment().add('day', -parseInt(Math.random()*30)).format("YYYY-MM-DD (dd)"),
      money: parseInt(Math.random()*300),
      recorder: Math.random()>0.5?"Honda":"Sanae",
      note: Math.random()>0.5?"[早餐] 豆漿+漢堡":"[午餐] 麥當勞",
      payer: Math.random()>0.5?"Honda":"Sanae",
      owner: Math.random()>0.5?"Honda":"Sanae"
    })
  return a;
}

window.createRecordTable = function(){
  data = fakeDatas(10);
  user = "Honda";
  
  var trs = data.map(function(item){

    var status = "";
    var popup = "<a class='item'><div class='ui horizontal label'>記錄人："+item.recorder+"</div></a>";
    if(window.current_user == item.owner && item.owner != item.payer) {
      status = "negative";
      popup += "<a class='item'><div class='ui red horizontal label'>債權人："+item.payer+"</div></a>";
    }
    else if(window.current_user == item.payer && item.owner != item.payer) {
      status = "positive"
      popup += "<a class='item'><div class='ui green horizontal label'>債務人："+item.owner+"</div></a>";
    }

    popup = "<div class='ui divided selection list'>"+popup+"</div>";
    

    var tr = 
      "<tr data-html=\""+popup+"\" class='"+status+" emmo-popup'>"+
        "<td>"+item.time+"</td>"+
        "<td>"+item.money+"</money>"+
        "<td>"+item.note+"</td>"+
        "<td><i class=\"close icon emmo-hover-rotate\"></i></td>"+
      "</tr>";
    return tr;
  });
  console.log(trs)
  $("#bookRecordTable tbody").html(trs.join(''));
  activeEmmoPopup();

}

$(function(){
  $('.emmo-web-sidebar')
    .sidebar({
      //overlay: true
    })
    .sidebar('attach events', '#emmo-add-record-button')
  $('.emmo-web-sidebar .close.icon').click(function(){
    $('.emmo-web-sidebar').sidebar('hide');
  });

  
  createRecordTable();

  $("#emmo-record-time>.dropdown>.menu").each(function(){
    var m = moment()
    var items = ""

    for(var i=0;i<60;i++) {
      //active = (i==0)?"active":"";
      items += '<div class="item " data-value="'+m.format("YYYY-MM-DD")+'">'+m.format("YYYY-MM-DD (dd)")+'</div>'
      m.add('day', -1);
    }
    //window.a=items;
    //$(items).find(".item:first").addClass("active").html()
    $(this).html(items);

  });

  $('.ui.dropdown').dropdown({
    //on: 'hover'
  });
  
  $("#emmo-record-time>.dropdown").dropdown("set selected", moment().format("YYYY-MM-DD (dd)"))

    //.sidebar('attach events', 'body')

});
</script>

app/views/friends/index.html.erb
<% provide :sidebar_active_item, 'friends' %>
<% provide :page_title_text, '我的朋友' %>
<% provide :page_title_icon, 'star' %>

<div class="ui form">
  <div class="inline fields">
    <div class="field">
      <label>邀請好友</label>
      <!--<div class="ui action input">-->
        <input type="text" placeholder="Friend's e-mail...">
        <div class="ui icon button"><i class="add icon"></i></div>
      <!--</div>-->
    </div>
  </div>
</div>



<div class="ui four items">
  <div class="item emmo-compact-item">
    <div class="image">
      <img src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
      <a class="star ui corner label">
        <i class="close icon emmo-hover-rotate"></i>
      </a>
    </div>
    <div class="content">
      <div class="name">Cute Dog</div>
      <p class="description">
        <a class="ui red circular label">
          欠我
        </a> 800元</p>
    </div>
  </div>
  <div class="item emmo-compact-item">
    <div class="image">
      <img src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
      <a class="star ui corner label">
        <i class="close icon"></i>
      </a>
    </div>
    <div class="content">
      <div class="name">Faithful Dog</div>
      <p class="description">
      <a class="ui green circular label">
          欠他
        </a> 80元</p>
    </div>
  </div>
  <div class="item emmo-compact-item">
    <div class="image">
      <img src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
      <a class="star ui corner label">
        <i class="close icon"></i>
      </a>
    </div>
    <div class="content">
      <div class="name">Silly Dog</div>
      <p class="description">
        <a class="ui red circular label">
          欠我
        </a> 800元</p>
    </div>
  </div>
  <div class="item emmo-compact-item">
    <div class="image">
      <img src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
      <a class="star ui corner label">
        <i class="close icon"></i>
      </a>
    </div>
    <div class="content">
      <div class="name">Happy Dog</div>
      <p class="description">
        <a class="ui red circular label">
          欠我
        </a> 800元</p>
    </div>
  </div>
</div>

</div>

app/views/layouts/_sidebar.html.erb
<script>
$(function(){
  var sidebar_active_item = '<%= yield :sidebar_active_item %>';
  $('#sidebar-'+sidebar_active_item).addClass('active');
});
</script>

<div class="emmo-box emmo-sidebar"> 
  <div class="ui secondary vertical pointing menu" style="width: 100%">
    <a id="sidebar-books" class="item purple" href="/books">
      <i class="book icon"></i> 帳本
    </a>
    <a id="sidebar-notices" class="item blue">
      <i class="legal icon"></i> 債本
    </a>
    <a id="sidebar-friends" class="item green" href="/friends">
      <i class="star icon"></i> 好友
    </a>
    <a id="sidebar-setting" class="item orange" href="/setting">
      <i class="wrench icon"></i> 設定
    </a>
    <a id="sidebar-about" class="item red" href="/about">
      <i class="umbrella icon"></i> 關於
    </a>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="ui fixed transparent inverted main menu">
  <div class="emmo-container">

    <a class="launch item"><i class="icon list layout"></i> Content</a>


    <div class="title item">
      <b>Emmo</b>
    </div>
    <!--
    <div class="disabled icon item"><i class="left arrow icon"></i></div>
    
    <div class="section ui dropdown link item">
      <span class="count">1 of 4</span>
      <div class="menu">
        
          <div class="active item">
            <a href="/index.html">1. Introduction</a>
          </div>
        
          <div class="item">
            <a href="/collection.html">2. UI Collections</a>
          </div>
        
          <div class="item">
            <a href="/element.html">3. UI Elements</a>
          </div>
        
          <div class="item">
            <a href="/module.html">4. UI Modules</a>
          </div>
        
      </div>
    </div>
    
    <a class="icon item" href="/collection.html"><i class="right arrow icon"></i></a>
    
    -->
    <div class="right menu">
      
      <a class="icon item" title="註冊新帳號" href="#">
        <i class="icon magic"></i>
        註冊
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emmo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'fav.ico' %>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <script>
    window.current_user = '<%= current_user.name %>';
  </script>
</head>
<body class="emmo-sprinkles-bg">

<% #render "layouts/topbar" %>


<div class="emmo-container ">
  <div class="ui text menu emmo-float-right">

    <a class="active item">
      <!-- <i class="user icon"></i> -->
      <img class="ui avatar image" src="<%= current_user.gravatar_url %>" style="display: inline-block" />
      <%= current_user.name %>
    </a>

    <%# form_for(:session, url: session_path, :method => :delete) do |f| %>
    <a class="item">
      
      <%# f.button_to "登出", :method => 'delete' %>
      <div class="ui input">

        <!-- <i class="forward mail icon"></i>  -->
        <%= button_to "登出", sessions_path, class: '', method: 'delete'   %>
      </div>
    </a>
    <% #end %>
  </div>
</div>

<div class="emmo-header-segment ">
  <div class="emmo-container">
    <a href="/home" class="ui text" style="text-decoration: none;">
      <h2 class="ui header">
        <i class="circular magic icon"></i>
        Emmo - Let's account!
      </h2>
    </a>
  </div>
</div>

<div class="emmo-container">
  <div class="pure-g-r ui piled segment">
    <div class="pure-u-1-4">
        
      <%= render "layouts/sidebar" %>


    </div>
    <div class="pure-u-3-4">
      <div class="emmo-box">
        <div class=" emmo-main">
          

          <h2 class="ui dividing header large">
            <i class="<%= yield :page_title_icon  %> icon"></i>
            <%= yield :page_title_text  %>
          </h2>

          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>






</body>
</html>

app/views/layouts/pure.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emmo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'fav.ico' %>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->


</head>
<body class="emmo-sprinkles-bg">

<div class="emmo-container">
  <%= yield %>
</div>


</body>
</html>

app/views/settings/index.html.erb
<% provide :sidebar_active_item, 'setting' %>
<% provide :page_title_text, '我的設定' %>
<% provide :page_title_icon, 'wrench' %>

<div class="ui basic accordion">
  <div class="title">
    <i class="dropdown icon"></i>
    帳本分類管理
  </div>
  <div class="content">
    <table class="ui table segment">
    <thead>
      <tr><th>分類名稱</th>
      <th>備註</th>
    </tr></thead>
    <tbody>
      <tr>
        <td>回家車費</td>
        <td>行</td>     
      </tr>
    </tbody>
    <tfoot>
      <tr><th colspan="3">
        <div class="ui form">
          <div class="inline fields">
            <div class="field">
                <input type="text" placeholder="分類名稱">
                <input type="text" placeholder="備註">
                <!--<div class="ui selection dropdown">
                  <input type="hidden" name="belong">
                  <div class="default text">分類隸屬</div>
                  <i class="dropdown icon"></i>
                  <div class="menu ui transition hidden">
                    <div class="item" data-value="eat">食</div>
                    <div class="item" data-value="clothes">衣</div>
                    <div class="item" data-value="house">住</div>
                    <div class="item" data-value="traffic">行</div>
                    <div class="item" data-value="sport">運動</div>
                    <div class="item" data-value="amusement">娛樂</div>
                    <div class="item" data-value="treatment">醫療</div>
                    <div class="item" data-value="other">其他</div>
                  </div>
                 </div> -->
              <div class="ui red labeled small icon button"><i class="angle right icon"></i>新增分類</div>
            </div>
          </div>
        </div>
      </th>
    </tr></tfoot>
  </table>
  </div>
</div>
<br>
<div class="inline field">
  <div class="ui toggle checkbox">
    <input type="checkbox" value="on">
    <label>朋友是否可以幫自己記帳</label>
  </div>
</div>
<br>
<div class="ui form">
  <div class="inline fields">
    <div class="field">
      <label>我的大頭貼</label>
     <input type="text" placeholder="...">
      <div class="ui red labeled small icon button"><i class="angle right icon"></i>選擇檔案</div>
    </div>
  </div>
</div>


<script>
$(function(){
  $('.ui.accordion').accordion();
});

$('.ui.selection.dropdown')
  .dropdown()
;

$('.ui.checkbox')
  .checkbox()
;
</script>

app/views/shared/_error_messages.html.erb
<% if @errors and @errors.any? then %>
  <div class="ui error message">
    <% #<i class="close icon"></i> %>
    <div class="header">
      <%= "發現了#{@errors.count}個錯誤！" %>
    </div>
    <ul class="list">
      <% @errors.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
  <script>
  $(function(){
    $('.field:has(.field_with_errors)').addClass('error');
    $('input').each(function(i, n){
      if( $(n).parent().is('.field_with_errors') )
        $(n).unwrap();
    })
  })
  </script>
<% end %>

app/views/static_pages/about.html.erb
<% provide :sidebar_active_item, 'about' %>
<% provide :page_title_text, '關於Emmo' %>
<% provide :page_title_icon, 'umbrella' %>


<div class="ui  column grid" style="display: block;">
  <div class="column">
    <div class="row">
      <div class="ui raised segment">
        <div class="ui purple ribbon label">Introduction</div>
        <p>這是一個簡易的記帳系統，除了普通的記帳功能，另外還提供了債務記錄功能，以及好友圈的互相幫忙記帳功能，功能持續改進與增加，謝謝支持呦</p>
        <div class="ui red ribbon label">Author</div>
        <h2 class="ui medium header">
          <div class="ui circular rotate reveal small left image">
            <img class="visible content" src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
            <img class="hidden content" src="https://secure.gravatar.com/avatar/9fd5e8de673bdb25c49dc10076f50f50">
          </div>
          <div class="content">
            Honda Dai
            <div class="sub header">I am a student.</div>
          </div>
        </h2>
        <h2 class="ui medium header">
          <div class="ui circular rotate reveal small left image">
            <img class="visible content" src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
            <img class="hidden content" src="https://secure.gravatar.com/avatar/3140ab6dbe121d199eb21aa5c28992af">
          </div>
          <div class="content">
            ChianYa Hong
            <div class="sub header">I am a student.</div>
          </div>
        </h2>
        
      </div>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:page_title, 'Home') %>


<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/user/login.html.erb
<% provide(:hide_header_segment, true) %>
<% provide(:hide_topbar, true) %>
<% provide(:hide_sidebar, true) %>
<% provide(:page_title, 'Login') %>

<div class="ui modal active" style="top: 20%">
    <div class="header">
      登入 Emmo
    </div>
    <div class="content emmo-pusheen-bg pure-g-r">
      <div class="pure-u-2-5">
        <img class="ui medium image" src="http://25.media.tumblr.com/tumblr_m5mlt6a0EH1qhy6c9o1_400.gif">
      </div>
      <div class="pure-u-3-5">
        <div class="ui header">開始記帳吧！</div>
        

        <div class="ui form segment emmo-pusheen-dark-bg">
          <div class="field">
            <label>Username</label>
            <div class="ui left labeled icon input">
              <input type="text" placeholder="Username">
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <label>Password</label>
            <div class="ui left labeled icon input">
              <input type="password">
              <i class="lock icon"></i>
            </div>
          </div>
          <div class="ui error message">
            <div class="header">We noticed some issues</div>
          </div>
          <div class="ui buttons">
            <div class="ui blue submit button">登入</div>
            <div class="or"></div>
            <div class="ui red submit button">註冊</div>
          </div>

        </div>

      </div>
    </div>
    <div class="actions">
      <!--
      <div class="ui black button">
        Cancel
      </div>
      <div class="ui positive right labeled icon button">
        Add Photo
        <i class="checkmark icon"></i>
      </div>
      -->
    </div>
  </div>

app/views/users/create.html.erb
<% provide(:page_title, '') %>



<div class="ui modal active emmo-active-model" style="">
    <div class="header">
      註冊成功！ <%= @user.name %> 歡迎你！
    </div>
    <div class="content emmo-pusheen-bg pure-g-r">
      <div class="pure-u-1-1 ">
        <img class="ui huge image emmo-center" src="http://media.catmoji.com/post/w7j/thank-you-for-following-me-pusheen-the-cat.gif">
      </div>
    </div>
    <div class="actions">
      <a href="/" class="ui button blue">馬上開始使用</a>
    </div>
  </div>